<a href="https://colab.research.google.com/github/blackpearl-09/TIL/blob/main/Mid_project_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install beautifulsoup4==4.7.1

Requirement already satisfied: beautifulsoup4==4.7.1 in c:\programdata\anaconda3\lib\site-packages (4.7.1)
Requirement already satisfied: soupsieve>=1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4==4.7.1) (1.8)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
# !pip install IPython 
from IPython.display import Image

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from numpy import dot  #numpy array 끼리 곱할 때 사용
from numpy.linalg import norm #벡터의 크기 측정하는 함수
import numpy as np

In [ ]:
import pandas as pd

df = pd.read_csv('https://github.com/TaewoongKong/code_sharing/blob/master/startup-benefits.csv?raw=True')
df

,회사명,개인장비,통근교통,자기계발,식사간식,근무형태,보험의료,연차휴가,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,8percent,"맥북,아이맥",NaN,"도서구입비,스터디지원,자기계발비","맥주,커피/음료,특식지원","09:00-18:00,10:00-19:00,유연근무","4대보험,건강/종합검진","리프레시 휴가,자율 휴가",제작자 블로그,김문과의 데이터,https://data101.oopy.io/
1,9minteractive,듀얼모니터,NaN,NaN,"간식,석식,커피/음료",NaN,"4대보험,건강/종합검진",NaN,NaN,NaN,NaN
2,april,"데스크탑,랩탑",역세권,NaN,"중식,커피/음료",09:30-18:30,"4대보험,경조사비","생일/결혼기념일 휴가,자율 휴가",NaN,NaN,NaN
3,atostudy,랩탑,주거지원,"도서구입비,동아리지원,스터디지원,직무교육비",간식,10:00-19:00,4대보험,"자기계발 휴가,장기근속포상/휴가,출산 휴가",NaN,NaN,NaN
4,bagelcode,"듀얼모니터,맥북",NaN,게임비용지원,"석식,조식,중식",10:00-19:00,"4대보험,경조사비,출산비",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
98,within,"듀얼모니터,맥북,아이맥,종합적지원",야근교통비,"도서구입비,자사크레딧지원","석식,조식,중식,커피/음료","09:00-18:00,특별휴무/퇴근일","4대보험,경조사비","생리 휴가,월차,자율 휴가",NaN,NaN,NaN
99,yanolja,"듀얼모니터,맥북,아이맥",야근교통비,"도서구입비,체력단련비","명절상품권/상여금,생일상여,중식,커피/음료,특식지원",자율출퇴근,"4대보험,건강/종합검진,경조사비,의료실비보험","월차,출산 휴가",NaN,NaN,NaN
100,yellomobile,"듀얼모니터,맥북",NaN,직무교육비,"커피/음료,특식지원","09:00-18:00,특별휴무/퇴근일","4대보험,건강/종합검진,경조사비",NaN,NaN,NaN,NaN
101,yogiyo,NaN,NaN,"도서구입비,동아리지원,직무교육비",간식,10:00-19:00,"4대보험,경조사비","자율 휴가,특별/포상 휴가",NaN,NaN,NaN
102,zipdoc,듀얼모니터,NaN,동아리지원,커피/음료,"08:00-17:00,09:00-18:00,10:00-19:00","4대보험,경조사비,의료실비보험",자율 휴가,NaN,NaN,NaN

In [ ]:
#불필요한 열 제거
df.drop(['Unnamed: 8','Unnamed: 9','Unnamed: 10'], axis=1, inplace=True)

#띄어쓰기나 특수기호를 넣을경우, countervectorizer가 자동으로 삭제 
# -> 비교대상이 없어서져 코사인유사도 계산 시 들어가는 vector값이 NaN 나옴. 

# 문자열 empty로 채워줌. 
df.fillna(value="Empty", inplace=True)

-  fillna(value = 채우고자 하는 변수를 집어넣는 곳으로 int, float, string 어떤 것도 다 가능)

  - 1-1) pd.DataFrame.fillna(value=int)
  - 1-2) pd.DataFrame.fillna(value=dict)
  - 1-3) pd.DataFrame.fillna(value=pd.Series)
  - 1-4) pd.DataFrame.fillna(value=pd.DataFrame)

In [ ]:
df[['통근교통']].fillna(value=pd.DataFrame({'통근교통':[1,2,3,4,5]}))

      통근교통
0        1
1        2
2      역세권
3     주거지원
4        5
..     ...
98   야근교통비
99   야근교통비
100    NaN
101    NaN
102    NaN

[103 rows x 1 columns]

In [ ]:
# type(np.nan)
df

,회사명,개인장비,통근교통,자기계발,식사간식,근무형태,보험의료,연차휴가
0,8percent,"맥북,아이맥",Empty,"도서구입비,스터디지원,자기계발비","맥주,커피/음료,특식지원","09:00-18:00,10:00-19:00,유연근무","4대보험,건강/종합검진","리프레시 휴가,자율 휴가"
1,9minteractive,듀얼모니터,Empty,Empty,"간식,석식,커피/음료",Empty,"4대보험,건강/종합검진",Empty
2,april,"데스크탑,랩탑",역세권,Empty,"중식,커피/음료",09:30-18:30,"4대보험,경조사비","생일/결혼기념일 휴가,자율 휴가"
3,atostudy,랩탑,주거지원,"도서구입비,동아리지원,스터디지원,직무교육비",간식,10:00-19:00,4대보험,"자기계발 휴가,장기근속포상/휴가,출산 휴가"
4,bagelcode,"듀얼모니터,맥북",Empty,게임비용지원,"석식,조식,중식",10:00-19:00,"4대보험,경조사비,출산비",Empty
...,...,...,...,...,...,...,...,...
98,within,"듀얼모니터,맥북,아이맥,종합적지원",야근교통비,"도서구입비,자사크레딧지원","석식,조식,중식,커피/음료","09:00-18:00,특별휴무/퇴근일","4대보험,경조사비","생리 휴가,월차,자율 휴가"
99,yanolja,"듀얼모니터,맥북,아이맥",야근교통비,"도서구입비,체력단련비","명절상품권/상여금,생일상여,중식,커피/음료,특식지원",자율출퇴근,"4대보험,건강/종합검진,경조사비,의료실비보험","월차,출산 휴가"
100,yellomobile,"듀얼모니터,맥북",Empty,직무교육비,"커피/음료,특식지원","09:00-18:00,특별휴무/퇴근일","4대보험,건강/종합검진,경조사비",Empty
101,yogiyo,Empty,Empty,"도서구입비,동아리지원,직무교육비",간식,10:00-19:00,"4대보험,경조사비","자율 휴가,특별/포상 휴가"
102,zipdoc,듀얼모니터,Empty,동아리지원,커피/음료,"08:00-17:00,09:00-18:00,10:00-19:00","4대보험,경조사비,의료실비보험",자율 휴가


- string을 대체하기 위해 pandas의 replace 사용 
 - to_replace(from): 교체해야하는 DataFrame의 값 
 - value(to): to_replace와 일치하는 모든 값을 바꿀 값 
 - 문자열 일부만 치환하고 싶은 경우는 regex=True를 설정해 정규 표현식으로 일부만 치환

In [ ]:

# 문자열 replace는 regular expression(정규표현식) regex=True 설정.
df.replace(to_replace='/', value='', regex=True, inplace=True)

# 근무형태(문자열) 데이터 전처리
df['근무형태'] = df['근무형태'].str.replace('[0-9]', '')
# df['근무형태'] = df['근무형태'].str.replace(':-:,', '')
# df['근무형태'] = df['근무형태'].str.replace(':-:', 'Empty')
# df['연차휴가'] = df['연차휴가'].str.replace(' ', '')
# df['근무형태'] = df['근무형태'].str.replace(' ', 'Empty')
df

,회사명,개인장비,통근교통,자기계발,식사간식,근무형태,보험의료,연차휴가
0,8percent,"맥북,아이맥",Empty,"도서구입비,스터디지원,자기계발비","맥주,커피음료,특식지원",":-:,:-:,유연근무","4대보험,건강종합검진","리프레시 휴가,자율 휴가"
1,9minteractive,듀얼모니터,Empty,Empty,"간식,석식,커피음료",Empty,"4대보험,건강종합검진",Empty
2,april,"데스크탑,랩탑",역세권,Empty,"중식,커피음료",:-:,"4대보험,경조사비","생일결혼기념일 휴가,자율 휴가"
3,atostudy,랩탑,주거지원,"도서구입비,동아리지원,스터디지원,직무교육비",간식,:-:,4대보험,"자기계발 휴가,장기근속포상휴가,출산 휴가"
4,bagelcode,"듀얼모니터,맥북",Empty,게임비용지원,"석식,조식,중식",:-:,"4대보험,경조사비,출산비",Empty
...,...,...,...,...,...,...,...,...
98,within,"듀얼모니터,맥북,아이맥,종합적지원",야근교통비,"도서구입비,자사크레딧지원","석식,조식,중식,커피음료",":-:,특별휴무퇴근일","4대보험,경조사비","생리 휴가,월차,자율 휴가"
99,yanolja,"듀얼모니터,맥북,아이맥",야근교통비,"도서구입비,체력단련비","명절상품권상여금,생일상여,중식,커피음료,특식지원",자율출퇴근,"4대보험,건강종합검진,경조사비,의료실비보험","월차,출산 휴가"
100,yellomobile,"듀얼모니터,맥북",Empty,직무교육비,"커피음료,특식지원",":-:,특별휴무퇴근일","4대보험,건강종합검진,경조사비",Empty
101,yogiyo,Empty,Empty,"도서구입비,동아리지원,직무교육비",간식,:-:,"4대보험,경조사비","자율 휴가,특별포상 휴가"
102,zipdoc,듀얼모니터,Empty,동아리지원,커피음료,":-:,:-:,:-:","4대보험,경조사비,의료실비보험",자율 휴가

In [ ]:
df['근무형태'] = df['근무형태'].str.replace(':-:', 'Empty')
df['연차휴가'] = df['연차휴가'].str.replace(' ', '')
df['근무형태'] = df['근무형태'].str.replace(' ', 'Empty')

#### 추가정보: 파이썬 정규표현식 치환(regular expression operation)

In [ ]:
import re
#re.sub(pattern, replace, text)



txt = "Hi, my phone number is 089992654231. I am 34 years old. I live in 221B Baker Street. I have 1,000,000 in my bank account."

def processString3(txt):
  txt = re.sub('[0-9]', 'X', txt)
  print(txt)
  
processString3(txt)

Hi, my phone number is XXXXXXXXXXXX. I am XX years old. I live in XXXB Baker Street. I have X,XXX,XXX in my bank account.

In [ ]:
# 유저 input 받기 (예시, 추후 input 받아올 것)
# .lower() 모든 변수에 적용가능

while True:
    company = input('회사명을 영문으로 입력해주세요(종료 : q) : ').lower().replace(" ","")
    if company == 'q':
        company = '다시 실행해주세요.'
        break
    if company not in df_temp['회사명'].values:
        print('해당 회사에 대한 정보가 없습니다.')
        continue
        # while 문 시작으로 돌아감
    break
print(company)

# isalpha(): 모든 원소가 문자일 경우 True, 하나라도 아니면 False
# isdigit(): 모든 원소가 정수일 경우 True, 하나라도 아니면 False

In [ ]:
print('[우선 순위 선택 항목: (1:개인장비, 2:통근교통, 3:자기계발, 4:식사간식, 5:근무형태, 6:보험의료, 7:연차휴가)] / 종료 : q')
dict_category = {'1':'개인장비', '2':'통근교통', '3':'자기계발', '4':'식사간식', '5':'근무형태', '6':'보험의료', '7':'연차휴가'}
keys = list(dict_category.keys())
while True:
    first = input('1순위 선택 항목을 입력해주세요 : ' )
    if first == 'q':
        first = '실행이 종료됩니다. 다시 실행해주세요.'
        break
    if first not in keys:
        print('선택 항목을 벗어났습니다.')
        continue
    break
while True:
    second = input('2순위 선택 항목을 입력해주세요 : ' )
    if second == 'q':
        second = '실행이 종료됩니다. 다시 실행해주세요.'
        break
    if second not in keys:
        print('선택 항목을 벗어났습니다.')
        continue
    elif second == first:
        print('1순위 항목과 중복됩니다.')
        continue
    break
while True:
    third = input('3순위 선택 항목을 입력해주세요 : ' )
    if third == 'q':
        third = '실행이 종료됩니다. 다시 실행해주세요.'
        break
    if third not in keys:
        print('선택 항목을 벗어났습니다.')
        continue
    elif third == first:
        print('1순위 항목과 중복됩니다.')
        continue
    elif third == second:
        print('2순위 항목과 중복됩니다.')
        continue
    break
    
first = dict_category[first]
second = dict_category[second]
third = dict_category[third]
print(company, first, second, third)

회사명을 영문으로 입력해주세요(종료 : q) : april
april
[우선 순위 선택 항목: (1:개인장비, 2:통근교통, 3:자기계발, 4:식사간식, 5:근무형태, 6:보험의료, 7:연차휴가)] / 종료 : q
1순위 선택 항목을 입력해주세요 : 1
2순위 선택 항목을 입력해주세요 : 2
3순위 선택 항목을 입력해주세요 : 4
april 개인장비 통근교통 식사간식

### 텍스트 분석 시작, 문자열을 수치 벡터로 만드는 것.
 

- CountVectorizer : 각 텍스트에서 단어 출현 횟수를 카운팅하여 수치벡터화/ 모두 소문자로 변환시킴

  - 출현 횟수를 카운팅하려면 단어사전 필요 -> from sklearn.feature_extraction.text import CountVectorizer
  - 조사, 혹은 지시대명사와 같이 특별한 의미를 지니지 않는데 자주 사용되는 단어는 카운팅에서 높은 횟수를 가지게 되지만, 
실질적으론 의미가 없는 데이터라서 이걸 해결하는 방법으로 나온 것이 바로 TF-IDF   
    
    
    
### TfidfVectorizer : TF-IDF라는 값을 사용하여 CountVectorizer의 단점을 보완함

- TF?
 - Term Frequency의 약자.
 - 1개 문서 안에서 특정 단어의 등장 빈도를 의미
 - 전체 단어수에서 특정 단어가 얼마나 사용되었는지를 파악하여, 해당 문서의 성질을 파악하는 지표로 사용
 - 주로 형태소 단위로 나눔
 
 
- DF?
 - Document Frequency의 약자입니다.
 - 특정 단어가 나타나는 문서 수
 - DF는 한 단어가 전체 문서 집합 내에서 얼마나 공통적으로 많이 등장하는지를 나타내는 값 
 - TF는 주체가 단어라면, DF는 주체가 문서 
 
- IDF? 
 - DF에서 역수 변환을 해준 값
 - 특정 단어가 모든 문서에 다 등장하는 흔한 단어 즉 DF값이 클 수록, tf-idf의 가중치 값을 낮춰주기 위해서 DF값에 역수를 취한 값이 바로 IDF.
 
 
 
 
 ++ 플러스! 특정 단어가 전체의 문서 안에 존재하지 않을 경우,  분모가 0이 되어버리는 상황이 발생. 
  - 이를 방지 하기 위해 분모에 1을 더해줌

In [ ]:
#유저 input 받기 (예시, 추후 input으로 받아올 것)

inputs = [first, second, third]

weights = {0:0.5, 1:0.3, 2:0.2}

#for반복문에 index, input <- 두개의 인자를 넣은 이유 
#enumerate: 순서가 있는 자료형(리스트, 튜플, 문자열)을 입력으로 받아 인덱스 값을 포함하는 enumerate 객체를 돌려 줌.


df_temp = df.copy()
df_final = df_temp[['회사명']]
for index, inPut in enumerate(inputs):
    corpus = []
    for value in df[inPut]:  #회사명을 하나씩 value에 넣고
        corpus.append(value)
    vector = CountVectorizer() #countvetorizer 생성
    arr_column = vector.fit_transform(corpus).toarray() #corpus(inPut의 value)로부터 각 단어의 빈도수를 기록
    print(vector.vocabulary_) 
    
    #print(pd.DataFrame(arr_equip).head())
    
    #cosine similarity (기준을 정해서, 유사도를 구해보자)
    #유저가 선택한 기업의 index를 기준으로, 나머지 docs(회사)들의 상대적인 유사도 도출
    
    #그러려면 선택한 회사의 index 번호를 알아야 한다. 그 회사의 행렬을 뽑기 위해서는
    # pandas에 있는, index.values: Return an array representing the data in the Index.
    picked_index = df.index.values[df['회사명']==company][0]
    
    #코사인 유사도 계산함수. !=cosine similarity 공식
    def cos_sim(A,B): 
        np.seterr(divide = 'ignore', invalid = 'ignore') #유효하지 않은 부동 소수점 연산 처리
        return dot(A, B)/(norm(A)*norm(B))
    
# Norm은 벡터의 길이 혹은 크기를 측정하는 방법(함수). 
# Norm이 측정한 벡터의 크기는 원점에서 벡터 좌표까지의 거리 혹은 Magnitude.    
    
    sim_list = []
    
    doc1 = arr_column[picked_index] # 회사명['유저가 선택한 회사의 index번호']
    for doc2 in arr_column : #상대열  
        sim_list.append(cos_sim(doc1,doc2)) #유저가 선택한 회사와 상대 회사들의 코사인유사도 계산
        
    df_temp[inPut] = sim_list #df_temp (만들어 놓은 new데이터프레임) (유저가 입력한 기준 열의) value값을 코사인유사도값으로 대체(위에서 각 inPut의 코사인유사도 구한것)
    df_final[inPut] = [x*weights[index] for x in sim_list]  #위에서 설정한 weight와 index(enumerate로 나온)로 계산, 위의 리스트에서 코사인유사도 값을 하나씩 받아서 
    df_temp.head()
        
df_temp
        
df_final['Total'] = df_final[inputs].sum(axis=1)  


df_final= df_final.sort_values(by='Total', ascending=False)
df_final.head()
# df_final                
# 코사인 유사도 계산 함수. cosine_similarity는 df를 인풋으로 받으나, 이 함수는 numpy array를 input으로 받음.
# 분자가 0일 경우: RuntimeWarning: invalid value encountered in true_divide <- 해당 에러 발생...

{'맥북': 4, '아이맥': 8, '듀얼모니터': 2, '데스크탑': 1, '랩탑': 3, 'empty': 0, '스탠딩책상': 7, '사무용품': 6, '브랜드가구': 5, '안마의자': 9, '종합적지원': 12, '업무용폰': 10, '입사축하금': 11}
{'empty': 0, '역세권': 3, '주거지원': 8, '야근교통비': 2, '교통비지원': 1, '유류비지원': 5, '전기차구매시보험료지원': 7, '주차지원': 9, '자사서비스크레딧': 6, '영업활동비지원': 4}
{'맥주': 3, '커피음료': 12, '특식지원': 13, '간식': 1, '석식': 7, '중식': 11, '조식': 10, '과일': 2, '명절상품권상여금': 4, 'empty': 0, '외근식대': 8, '생일상여': 6, '복지몰': 5, '자사제품할인': 9}

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                회사명      개인장비  통근교통      식사간식     Total
2             april  0.500000   0.3  0.200000  1.000000
67       peoplefund  0.408248   0.0  0.126491  0.534739
47            madit  0.408248   0.0  0.081650  0.489898
79  simpleprojectco  0.408248   0.0  0.070711  0.478959
13    channelbreeze  0.353553   0.0  0.100000  0.453553